package channel

import (
	"crypto/ed25519"
	"encoding/binary"
	"gitlab.com/elixxir/crypto/hash"
)

// hashRequestInfo is a helper which handles hashing info for a channel lease response
func hashResponseInfo(userEdPub []byte, lease uint64) []byte {
	leaseBytes := make([]byte, 8)
	binary.BigEndian.PutUint64(leaseBytes, lease)
	h := hash.CMixHash.New()
	h.Write(leaseBytes)
	h.Write(userEdPub)
	return h.Sum(nil)
}

// SignResponse accepts a user's ed25519 pub key & a given lease and signs them with an ed25519 private key
func SignResponse(userEdPub []byte, lease uint64, pk ed25519.PrivateKey) []byte {
	hashed := hashResponseInfo(userEdPub, lease)
	return ed25519.Sign(pk, hashed)
}

// VerifyResponse verifies a signature generated by SignResponse, accepting the same info and a corresponding ed25519 public key
func VerifyResponse(sig, userEdPub []byte, lease uint64, pub ed25519.PublicKey) bool {
	hashed := hashResponseInfo(userEdPub, lease)
	return ed25519.Verify(pub, hashed, sig)
}
